insert into destinations (id, slug, country, title_en, title_vn, excerpt_en, excerpt_vn, body_en, body_vn, image, languages, currency) values
('hanoi', 'hanoi', 'Vietnam', 'Hanoi', 'Hà Nội', 'Layered capital of lakes, tube houses, and late-night pho.', 'Thủ đô nhiều lớp: hồ, phố cổ, phở đêm.', 'Hanoi is the slow pulse of the north: Hoan Kiem at first light, French-era villas, and a cuisine that argues over herbs. Use it as a hinge between the highlands and the coast.', 'Hà Nội là nhịp chậm của miền Bắc: Hồ Gươm lúc rạng đông, biệt thự Pháp, và một nền ẩm thực tranh luận về rau thơm.', '/media/dest-hanoi.jpg', 'Vietnamese, English', 'VND'),
('halong', 'ha-long', 'Vietnam', 'Ha Long Bay', 'Vịnh Hạ Long', 'Karst islands, jade water, overnight junks.', 'Đảo đá vôi, nước ngọc, thuyền overnight.', 'A UNESCO seascape of limestone towers. The honest way through is a small junk, a quiet cove, and enough time to watch the weather change.', 'Di sản UNESCO của những tháp đá vôi. Cách tử tế nhất là thuyền nhỏ, vịnh kín, và đủ thì giờ nhìn trời đổi.', '/media/hero-halong.jpg', 'Vietnamese, English', 'VND'),
('hoian', 'hoi-an', 'Vietnam', 'Hoi An', 'Hội An', 'Lantern town on the Thu Bon, tailor shops, tidal streets.', 'Phố đèn lồng trên sông Thu Bồn.', 'Hoi An still behaves like a trading port. Walk the Japanese Bridge after the day-trippers leave; eat cao lau; take a bicycle into the vegetable villages.', 'Hội An vẫn như một cảng thương. Đi Chùa Cầu khi khách ngày đã về; ăn cao lầu; đạp xe ra làng rau.', '/media/dest-hoian.jpg', 'Vietnamese, English', 'VND'),
('hue', 'hue', 'Vietnam', 'Hue', 'Huế', 'Imperial citadel, perfume river, tomb gardens.', 'Kinh thành, sông Hương, lăng tẩm.', 'Hue is ceremony without hurry: the citadel moat, Nguyen tombs in pine, and a court cuisine that still plates like a poem.', 'Huế là nghi lễ không vội: hào thành, lăng Nguyễn trong thông, ẩm thực cung đình.', '/media/unesco-hue.jpg', 'Vietnamese, English', 'VND'),
('sapa', 'sapa', 'Vietnam', 'Sapa', 'Sa Pa', 'Terraced valleys, Hmong and Dao villages, cold mornings.', 'Ruộng bậc thang, bản Mông và Dao.', 'Sapa rewards walking. Sleep in a timber lodge, follow a local guide through the terraces, and treat the weather as part of the itinerary.', 'Sa Pa dành cho người đi bộ. Ngủ nhà gỗ, theo hướng dẫn bản địa qua ruộng, xem thời tiết là một phần hành trình.', '/media/nature-sapa.jpg', 'Vietnamese, English', 'VND'),
('mekong', 'mekong-delta', 'Vietnam', 'Mekong Delta', 'Đồng bằng sông Cửu Long', 'Canals, floating markets, coconut shade.', 'Kênh rạch, chợ nổi, bóng dừa.', 'The delta is a working landscape. Travel by sampan, eat from the boat, and stay long enough to see a market assemble at dawn.', 'Đồng bằng là vùng đất làm việc. Đi xuồng, ăn trên sông, ở đủ lâu để thấy chợ họp lúc rạng sáng.', '/media/dest-mekong.jpg', 'Vietnamese, English', 'VND'),
('phuquoc', 'phu-quoc', 'Vietnam', 'Phu Quoc', 'Phú Quốc', 'Pepper farms, pale sand, a quieter west coast.', 'Hồ tiêu, cát nhạt, bờ tây yên.', 'Skip the east-coast strip if you can. The west still holds long empty beaches, night squid boats, and fish sauce houses that perfume the air.', 'Tránh dải đông nếu được. Bờ tây còn bãi dài, thuyền mực đêm, nhà nước mắm.', '/media/beach-phuquoc.jpg', 'Vietnamese, English', 'VND'),
('nhatrang', 'nha-trang', 'Vietnam', 'Nha Trang', 'Nha Trang', 'Bay city, islands, Cham towers inland.', 'Thành phố vịnh, đảo, tháp Chăm.', 'Use Nha Trang as a hinge on the central coast: a morning on the water, an afternoon at Po Nagar, then south toward the dunes.', 'Nha Trang là khớp nối miền Trung: sáng trên nước, chiều Po Nagar, rồi xuống cồn cát.', '/media/dest-nhatrang.jpg', 'Vietnamese, English', 'VND'),
('siemreap', 'siem-reap', 'Cambodia', 'Siem Reap', 'Xiêm Riệp', 'Gateway to Angkor, Tonle Sap, slow evenings.', 'Cửa ngõ Angkor, Biển Hồ.', 'Siem Reap is more than a launchpad. Dawn at Angkor Wat, then the quieter temples, then a boat onto Tonle Sap when the lake is high.', 'Xiêm Riệp không chỉ là bàn đạp. Bình minh Angkor, đền vắng hơn, rồi thuyền ra Biển Hồ.', '/media/dest-angkor.jpg', 'Khmer, English', 'USD'),
('bangkok', 'bangkok', 'Thailand', 'Bangkok', 'Bangkok', 'River city, teak houses, late trains of light.', 'Thành phố sông, nhà gỗ tếch.', 'Treat Bangkok as a river. Cross at dawn for Wat Arun, eat in a shophouse, and use the city as the southern gate to Indochina.', 'Hãy coi Bangkok là một dòng sông. Qua sông lúc rạng đông tới Wat Arun, ăn quán nhà phố.', '/media/dest-bangkok.jpg', 'Thai, English', 'THB');
