/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours/index'
import { Route as ToursSlugRouteImport } from './routes/tours/$slug'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as StaysIndexRouteImport } from './routes/stays/index'
import { Route as StaysSlugRouteImport } from './routes/stays/$slug'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsSlugRouteImport } from './routes/cars/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/stays/',
  path: '/stays/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysSlugRoute = StaysSlugRouteImport.update({
  id: '/stays/$slug',
  path: '/stays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/stays/': typeof StaysIndexRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/tours': typeof ToursIndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/stays': typeof StaysIndexRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/cars': typeof CarsIndexRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/stays/': typeof StaysIndexRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/search'
    | '/tours/'
    | '/tours/$slug'
    | '/destinations/'
    | '/destinations/$slug'
    | '/stays/'
    | '/stays/$slug'
    | '/cars/'
    | '/cars/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/search'
    | '/tours'
    | '/tours/$slug'
    | '/destinations'
    | '/destinations/$slug'
    | '/stays'
    | '/stays/$slug'
    | '/cars'
    | '/cars/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/contact'
    | '/login'
    | '/search'
    | '/tours/'
    | '/tours/$slug'
    | '/destinations/'
    | '/destinations/$slug'
    | '/stays/'
    | '/stays/$slug'
    | '/cars/'
    | '/cars/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ToursSlugRoute: typeof ToursSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  StaysIndexRoute: typeof StaysIndexRoute
  StaysSlugRoute: typeof StaysSlugRoute
  CarsIndexRoute: typeof CarsIndexRoute
  CarsSlugRoute: typeof CarsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/stays/'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$slug': {
      id: '/stays/$slug'
      path: '/stays/$slug'
      fullPath: '/stays/$slug'
      preLoaderRoute: typeof StaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AccountRoute,
  ContactRoute,
  LoginRoute,
  SearchRoute,
  ToursIndexRoute,
  ToursSlugRoute,
  DestinationsIndexRoute,
  DestinationsSlugRoute,
  StaysIndexRoute,
  StaysSlugRoute,
  CarsIndexRoute,
  CarsSlugRoute,
  ApiAuthSplatRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
